"""
Voucher Filtration & Stock Validation Automation
=================================================
DO NOT EDIT THIS FILE for campaign changes.
All campaign rules and file paths are in config.py

Usage:
    python voucher_filtration.py
"""

import pandas as pd
import openpyxl
import xlsxwriter
import os
import sys
import warnings
from datetime import date, datetime

warnings.filterwarnings('ignore')

# ── Load config ───────────────────────────────────────────────
try:
    from config import (
        PRICE_FILE, CONTENT_FILE, ZECOM_FILE, BAU_FILE, AM_EXCL_FILE,
        OUTPUT_FILE, ZECOM_COLS, MIN_PRICE_THRESHOLD, PRE_FILTER_RULES,
        CAMPAIGNS, STYLING
    )
except ImportError as e:
    print(f"ERROR: Could not load config.py — {e}")
    sys.exit(1)

TODAY = date.today()

print("=" * 60)
print("  VOUCHER FILTRATION AUTOMATION")
print(f"  Run date: {TODAY}")
print("=" * 60)


# ============================================================
# STEP 1: Load Price/Stock File
# ============================================================
print("\n▶ STEP 1: Loading Price/Stock file...")
if not os.path.exists(PRICE_FILE):
    print(f"  ERROR: File not found → {PRICE_FILE}"); sys.exit(1)

price_df = pd.read_excel(PRICE_FILE, sheet_name=0, header=0)
price_df = price_df.rename(columns={
    'SellerSku'  : 'SellerSKU',
    'ShopSku'    : 'ShopSKU',
    'Name'       : 'Product_Name',
    'SalePrice'  : 'Sale_Price_raw',
})
price_df['SellerSKU']     = price_df['SellerSKU'].astype(str).str.strip()
price_df['Product_ID']    = price_df.get('ProductId', '')
price_df['Status_Active'] = 'active'
price_df['Quantity']      = price_df.get('Quantity', 0)

# Drop price columns from price file — will use zeCOM AU/AV instead
price_df.drop(columns=[c for c in ['Price','Sale_Price_raw','Special_Price'] if c in price_df.columns], inplace=True)
print(f"  ✓ {len(price_df):,} SKUs loaded")


# ============================================================
# STEP 2: Map ALU_NO via Content File
# ============================================================
print("\n▶ STEP 2: Mapping ALU_NO via Content file...")
if not os.path.exists(CONTENT_FILE):
    print(f"  ERROR: File not found → {CONTENT_FILE}"); sys.exit(1)

content_df = pd.read_excel(CONTENT_FILE, sheet_name='content')[['Color_No', 'EAN']].copy()
content_df['EAN'] = content_df['EAN'].astype(str).str.strip()

def normalise_ean(v):
    return str(v).strip().split('.')[0].strip()

content_df['EAN_norm'] = content_df['EAN'].apply(normalise_ean)
content_df = content_df.drop_duplicates(subset='EAN_norm')

price_df['EAN_norm'] = price_df['SellerSKU'].apply(normalise_ean)
price_df = price_df.merge(content_df[['EAN_norm', 'Color_No']], on='EAN_norm', how='left')
price_df.rename(columns={'Color_No': 'ALU_NO'}, inplace=True)

matched = price_df['ALU_NO'].notna().sum()
print(f"  ✓ {matched:,} / {len(price_df):,} SKUs matched to ALU_NO")


# ============================================================
# STEP 3: Load zeCOM Tracking File
# ============================================================
print("\n▶ STEP 3: Loading zeCOM Tracking file (sheet: MY)...")
if not os.path.exists(ZECOM_FILE):
    print(f"  ERROR: File not found → {ZECOM_FILE}"); sys.exit(1)

wb_z = openpyxl.load_workbook(ZECOM_FILE, read_only=True, data_only=True)
ws_z = wb_z['MY']

zecom_records = []
for row in ws_z.iter_rows(min_row=5, values_only=True):
    style = row[ZECOM_COLS['style']] if len(row) > ZECOM_COLS['style'] else None
    if not style:
        continue
    def get(key):
        idx = ZECOM_COLS.get(key)
        return row[idx] if idx is not None and len(row) > idx else None
    zecom_records.append({
        'ALU_NO'       : str(style).strip(),
        'Launch_Date'  : get('launch_date'),
        'Status_Lazada': get('status_laz'),
        'Price'        : get('price'),         # AU
        'Special_Price': get('special_price'), # AV
        'Disc_Pct'     : get('disc_pct'),      # AW
        'Exclusion'    : get('exclusion'),     # AX
    })
wb_z.close()

zecom_df = pd.DataFrame(zecom_records).drop_duplicates(subset='ALU_NO')
print(f"  ✓ {len(zecom_df):,} styles loaded")

excl_counts = zecom_df['Exclusion'].value_counts()
print(f"  Exclusion values found:")
for val, cnt in excl_counts.items():
    print(f"    {cnt:>6,}x  {val}")

main_df = price_df.merge(zecom_df, on='ALU_NO', how='left')
print(f"  ✓ Merged: {len(main_df):,} rows")


# ============================================================
# STEP 4: Load BAU Voucher File (optional)
# ============================================================
main_df['Live_Date']  = None
main_df['Status_BAU'] = None

if BAU_FILE and os.path.exists(BAU_FILE):
    print("\n▶ STEP 4: Loading BAU Voucher file...")
    try:
        bau_raw = pd.read_excel(BAU_FILE, sheet_name='template', header=0)
        bau_df  = bau_raw.iloc[3:].copy()
        bau_df.columns = bau_raw.columns
        bau_df = bau_df.drop_duplicates(subset='SellerSKU')
        bau_df['SellerSKU'] = bau_df['SellerSKU'].astype(str).str.strip()
        live_col   = next((c for c in bau_df.columns if 'live' in str(c).lower()), None)
        status_col = next((c for c in bau_df.columns if str(c).strip().lower() == 'status'), None)
        cols = ['SellerSKU'] + ([live_col] if live_col else []) + ([status_col] if status_col else [])
        bau_sub = bau_df[cols].copy()
        if live_col:   bau_sub.rename(columns={live_col: 'Live_Date'}, inplace=True)
        if status_col: bau_sub.rename(columns={status_col: 'Status_BAU'}, inplace=True)
        main_df = main_df.merge(bau_sub, on='SellerSKU', how='left', suffixes=('', '_bau'))
        for col in ['Live_Date', 'Status_BAU']:
            if f'{col}_bau' in main_df.columns:
                main_df[col] = main_df[f'{col}_bau'].combine_first(main_df[col])
                main_df.drop(columns=[f'{col}_bau'], inplace=True)
        print(f"  ✓ BAU merged: {len(main_df):,} rows")
    except Exception as e:
        print(f"  WARNING: BAU file error (skipping) — {e}")
else:
    print("\n▶ STEP 4: BAU file not provided — Live_Date / Status_BAU will be blank")


# ============================================================
# STEP 5: AM Exclusion Flag
# ============================================================
am_excl_set = set()
if AM_EXCL_FILE and os.path.exists(AM_EXCL_FILE):
    print("\n▶ STEP 5: Loading AM Exclusion file...")
    am_df = pd.read_excel(AM_EXCL_FILE)
    am_excl_set = set(am_df.iloc[:, 0].dropna().astype(str).str.strip())
    print(f"  ✓ {len(am_excl_set):,} excluded ALU_NOs loaded")
else:
    print("\n▶ STEP 5: AM Exclusion file not provided — AM_Exclusion column will be blank")

main_df['AM_Exclusion'] = main_df['ALU_NO'].apply(
    lambda x: 'EXCLUDE' if pd.notna(x) and str(x).strip() in am_excl_set else ''
)


# ============================================================
# STEP 6: Eligibility Flags
# ============================================================
print("\n▶ STEP 6: Calculating eligibility...")

def check_eligibility(row):
    reasons = []

    # Status Lazada (zeCOM V col)
    if PRE_FILTER_RULES.get('status_lazada_must_be_yes'):
        sl = row.get('Status_Lazada')
        if pd.notna(sl) and str(sl).strip().upper() != 'YES':
            reasons.append('Status Lazada ≠ YES')

    # Status BAU (from BAU file)
    if PRE_FILTER_RULES.get('status_bau_must_be_yes'):
        sb = row.get('Status_BAU')
        if pd.notna(sb) and str(sb).strip().upper() != 'YES':
            reasons.append('Status BAU ≠ YES')

    # Future Live Date (from BAU file)
    if PRE_FILTER_RULES.get('future_live_date'):
        ld = row.get('Live_Date')
        if pd.notna(ld):
            ld_date = ld.date() if isinstance(ld, datetime) else ld
            if isinstance(ld_date, date) and ld_date > TODAY:
                reasons.append('Future Live Date')

    # Price / Special Price threshold
    if PRE_FILTER_RULES.get('min_price_threshold'):
        try:
            pv  = float(row['Price'])         if pd.notna(row.get('Price'))         else None
            spv = float(row['Special_Price'])  if pd.notna(row.get('Special_Price')) else None
            if (pv is not None and pv < MIN_PRICE_THRESHOLD) or \
               (spv is not None and spv < MIN_PRICE_THRESHOLD):
                reasons.append(f'Price or Special Price < {MIN_PRICE_THRESHOLD}')
        except:
            pass

    return 'ELIGIBLE' if not reasons else ' | '.join(reasons)

main_df['Eligibility'] = main_df.apply(check_eligibility, axis=1)
elig_count = (main_df['Eligibility'] == 'ELIGIBLE').sum()
print(f"  ✓ ELIGIBLE : {elig_count:,}")
print(f"  ✗ Flagged  : {len(main_df) - elig_count:,}")


# ============================================================
# STEP 7: Price vs Special Price Check
# ============================================================
def price_check(row):
    try:
        p  = row.get('Price')
        sp = row.get('Special_Price')
        if pd.isna(p) or pd.isna(sp): return 'NO DATA'
        return 'MATCH' if float(p) == float(sp) else 'MISMATCH'
    except:
        return 'NO DATA'

main_df['Price_vs_SpecialPrice'] = main_df.apply(price_check, axis=1)


# ============================================================
# STEP 8: Apply Campaign Rules (from config.py)
# ============================================================
print("\n▶ STEP 8: Applying campaign rules...")

def matches_campaign(excl_val, campaign):
    e  = str(excl_val).strip() if pd.notna(excl_val) else ''
    el = e.lower()
    mt = campaign['match_type']
    mv = [v.lower() for v in campaign['match_values']]
    ex = [v.lower() for v in campaign.get('excludes', [])]

    # Check match
    if mt == 'contains':
        matched = any(m in el for m in mv)
    else:  # exact
        matched = el in mv

    if not matched:
        return False

    # Check excludes
    if any(x in el for x in ex):
        return False

    return True

for camp in CAMPAIGNS:
    col = camp['output_col']
    main_df[col] = main_df.apply(
        lambda row: 'YES'
        if (row['Eligibility'] == 'ELIGIBLE'
            and row['AM_Exclusion'] != 'EXCLUDE'
            and matches_campaign(row.get('Exclusion'), camp))
        else '',
        axis=1
    )
    count = (main_df[col] == 'YES').sum()
    print(f"  {camp['name']}: {count:,} SKUs")


# ============================================================
# Output columns
# ============================================================
CAMP_COLS = [c['output_col'] for c in CAMPAIGNS]

OUT_COLS = [
    'Product_ID', 'Product_Name', 'SellerSKU', 'ALU_NO',
    'Status_Active', 'Quantity',
    'Price', 'Special_Price', 'Disc_Pct',
    'Live_Date', 'Status_BAU', 'Status_Lazada',
    'Price_vs_SpecialPrice', 'Exclusion',
    'AM_Exclusion', 'Eligibility',
] + CAMP_COLS

for c in OUT_COLS:
    if c not in main_df.columns:
        main_df[c] = ''

out_df       = main_df[OUT_COLS].copy()
mismatch_rows = out_df[
    (out_df['Eligibility'] == 'ELIGIBLE') &
    (out_df['Price_vs_SpecialPrice'] == 'MISMATCH')
]


# ============================================================
# STEP 9: Write Excel Output
# ============================================================
print(f"\n▶ STEP 9: Writing output → {OUTPUT_FILE}")
os.makedirs(os.path.dirname(OUTPUT_FILE) if os.path.dirname(OUTPUT_FILE) else '.', exist_ok=True)

wb = xlsxwriter.Workbook(OUTPUT_FILE, {'strings_to_numbers': False})

# ── Build formats ─────────────────────────────────────────────
S = STYLING
base = {'font_name': 'Arial', 'font_size': 9, 'valign': 'vcenter', 'border': 1, 'border_color': '#D1D5DB'}

def mkfmt(props):
    return wb.add_format({**base, **props})

FMT = {
    'header'   : mkfmt({'bold': True, 'bg_color': S['header_bg'], 'font_color': '#FFFFFF', 'text_wrap': True, 'align': 'center'}),
    'data'     : mkfmt({'bg_color': '#FFFFFF'}),
    'data_alt' : mkfmt({'bg_color': '#F8FAFC'}),
    'eligible' : mkfmt({'bg_color': S['eligible_bg'],  'font_color': S['eligible_font'],  'bold': True}),
    'flagged'  : mkfmt({'bg_color': S['flagged_bg'],   'font_color': S['flagged_font'],   'bold': True}),
    'amber'    : mkfmt({'bg_color': S['am_excl_bg'],   'font_color': S['am_excl_font'],   'bold': True}),
    'mismatch' : mkfmt({'bg_color': S['mismatch_bg'],  'font_color': S['mismatch_font']}),
    'match'    : mkfmt({'bg_color': S['match_bg'],     'font_color': S['match_font']}),
}

# Per-campaign YES formats
CAMP_FMTS = {}
for camp in CAMPAIGNS:
    CAMP_FMTS[camp['output_col']] = mkfmt({
        'bg_color': camp['cell_color'], 'font_color': camp['font_color'],
        'bold': True, 'align': 'center'
    })

COL_WIDTHS = {
    'Product_ID': 14, 'Product_Name': 32, 'SellerSKU': 18, 'ALU_NO': 14,
    'Status_Active': 11, 'Quantity': 10, 'Price': 12, 'Special_Price': 14,
    'Disc_Pct': 10, 'Live_Date': 14, 'Status_BAU': 12, 'Status_Lazada': 13,
    'Price_vs_SpecialPrice': 18, 'Exclusion': 30, 'AM_Exclusion': 14, 'Eligibility': 30,
}

def write_sheet(sheet_name, df, tab_color='#1E293B'):
    ws = wb.add_worksheet(sheet_name[:31])  # Excel max 31 chars
    ws.set_tab_color(tab_color)
    ws.freeze_panes(1, 0)
    ws.autofilter(0, 0, len(df), len(OUT_COLS) - 1)
    ws.set_row(0, 32)

    for ci, col in enumerate(OUT_COLS):
        ws.write(0, ci, col, FMT['header'])
        ws.set_column(ci, ci, COL_WIDTHS.get(col, 18))

    for ri, (_, row) in enumerate(df.iterrows(), 1):
        alt = ri % 2 == 0
        base_f = FMT['data_alt'] if alt else FMT['data']
        for ci, col in enumerate(OUT_COLS):
            val = row[col]
            if val is None or (isinstance(val, float) and pd.isna(val)):
                val = ''
            elif isinstance(val, (datetime, date)):
                val = str(val)[:10]

            if col == 'Eligibility':
                fmt = FMT['eligible'] if val == 'ELIGIBLE' else FMT['flagged']
            elif col == 'AM_Exclusion' and val == 'EXCLUDE':
                fmt = FMT['amber']
            elif col == 'Price_vs_SpecialPrice':
                fmt = FMT['match'] if val == 'MATCH' else (FMT['mismatch'] if val == 'MISMATCH' else base_f)
            elif col in CAMP_FMTS and val == 'YES':
                fmt = CAMP_FMTS[col]
            else:
                fmt = base_f

            ws.write(ri, ci, val, fmt)

# ── All SKUs sheet ────────────────────────────────────────────
print("  Writing 'All SKUs'...")
write_sheet('All SKUs', out_df, S['header_bg'])

# ── One sheet per campaign ────────────────────────────────────
for camp in CAMPAIGNS:
    col  = camp['output_col']
    name = camp['sheet_name']
    print(f"  Writing '{name}'...")
    write_sheet(name, out_df[out_df[col] == 'YES'], camp['tab_color'])

# ── Price Mismatch sheet ──────────────────────────────────────
print("  Writing 'Price Mismatch'...")
write_sheet('Price Mismatch', mismatch_rows, '#B91C1C')

# ── Summary sheet ─────────────────────────────────────────────
print("  Writing 'Summary'...")
ws_s = wb.add_worksheet('Summary')
ws_s.set_tab_color('#0F172A')
ws_s.set_column(0, 0, 42)
ws_s.set_column(1, 1, 16)
ws_s.set_column(2, 2, 56)

hf = wb.add_format({'font_name': 'Arial', 'font_size': 11, 'bold': True,
                     'bg_color': '#0F172A', 'font_color': '#FFFFFF',
                     'border': 1, 'align': 'center'})
ws_s.write(0, 0, 'Sheet / Campaign', hf)
ws_s.write(0, 1, 'SKU Count', hf)
ws_s.write(0, 2, 'Eligibility Criteria', hf)

summary_rows = [
    ('All SKUs (total)',      len(out_df),                              'All rows from Price/Stock file'),
    ('ELIGIBLE',             elig_count,                               'No pre-filter flags triggered'),
    ('Flagged',              len(out_df) - elig_count,                 'Status Lazada ≠ YES | Status BAU ≠ YES | Future Live Date | Price or SP < threshold'),
    ('AM Excluded',          (out_df['AM_Exclusion'] == 'EXCLUDE').sum(), 'In AM Exclusion list — campaign cols blank'),
] + [
    (camp['name'], (out_df[camp['output_col']] == 'YES').sum(),
     f"ELIGIBLE + not AM Excl + Exclusion {camp['match_type']} {', '.join(camp['match_values'])}")
    for camp in CAMPAIGNS
] + [
    ('Price Mismatch',       len(mismatch_rows),                       'ELIGIBLE rows where Price (AU) ≠ Special Price (AV)'),
]

row_colors = ['#F8FAFC','#DCFCE7','#FEE2E2','#FEF3C7'] + \
             [c['cell_color'] for c in CAMPAIGNS] + ['#FEE2E2']

for ri, (label, count, criteria) in enumerate(summary_rows, 1):
    bg = row_colors[ri - 1] if ri - 1 < len(row_colors) else '#F8FAFC'
    rf = wb.add_format({'font_name': 'Arial', 'font_size': 10, 'border': 1, 'bg_color': bg})
    nf = wb.add_format({'font_name': 'Arial', 'font_size': 10, 'border': 1,
                         'bold': True, 'align': 'center', 'bg_color': bg})
    ws_s.write(ri, 0, label,    rf)
    ws_s.write(ri, 1, count,    nf)
    ws_s.write(ri, 2, criteria, rf)

wb.close()

print(f"\n{'='*60}")
print(f"  ✅ DONE!  Output → {OUTPUT_FILE}")
print(f"  Total SKUs : {len(out_df):,}")
print(f"  Eligible   : {elig_count:,}")
for camp in CAMPAIGNS:
    print(f"  {camp['name']}: {(out_df[camp['output_col']]=='YES').sum():,}")
print(f"  Run date   : {TODAY}")
print(f"{'='*60}\n")
